version: '3.0'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
     - "8080:8080"
    volumes:
     - ./service-discovery:/app
     - ~/.m2:/root/.m2
    networks:
     - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
     - "8084:8080"
    volumes:
     - ./auth-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
     - "8083:8080"
    volumes:
     - ./gateway-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network
networks:
  app-network:
    driver: bridge